### ISSUE TITLE
Some names, gender seems to be incorrect

### ISSUE THREAD

**Issue by cbethter** [Theryston/gender-name#7]
Please, check these names, the gender seems to be incorrect.
DOMINIQUE, HELLEN, JAZA, JOYCE, JANE, ESTER, GEOVANE, GIOVANNE, IASMYN, JOYCE, JHENIFER, KEVIN, LUZITANIA, JOYCE, NEUZIMAR, NEUZIMAR, SHIRLEI, ROSECLER, THAIS, THAIS, THAIS, THAIRONE, TAIS.
Thanks.

**Comment by Theryston** [comment]
I'm checking these names. Maybe We'll have an new model to fix it

**Comment by Theryston** [comment]
A new release was launched, some changes were made, including an improvement in the current models, which resolves most of these errors

Some names may be difficult to discover the gender, or some may be unisex, in these cases, unisex names may be detected when both results are close.

**Example:**

Female: 0.6
Male: 0.4

You can see that although the API says the name is female, we can see that the model is not very sure whether it is female or male (since the difference is already only 0.1) in this case, generally the name is unisex

Release: [https://github.com/Theryston/gender-name/releases/tag/1.1.0](https://github.com/Theryston/gender-name/releases/tag/1.1.0)
